color: null
fieldLayouts:
  15e692e6-9f21-4426-92f0-4321881c32a2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-10-18T12:56:35+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 79643fba-2e17-446c-a4a0-2f697ed86465
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-18T13:00:02+00:00'
            elementCondition: null
            fieldUid: c798cdf5-723e-4cdc-8ac1-6c527b1a14a6 # Bovenkop
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a7f75e51-2cee-48bb-a17b-e968022c464a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-18T13:00:02+00:00'
            elementCondition: null
            fieldUid: d602da2a-239f-4f18-93fd-8047af89cdd0 # Kop
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 76edee0c-e516-45e2-8891-6c86cf8a3bb8
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-18T13:00:02+00:00'
            elementCondition: null
            fieldUid: 8f439fc2-311f-4f45-99c6-c482d129d1fd # Tag
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2a3c64f0-0814-4ce0-b876-5b7e3df130ef
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-18T13:00:02+00:00'
            elementCondition: null
            fieldUid: 437963f6-fffc-4014-921d-e13fd7b2315f # Tekst (uitgebreid)
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2fcc9364-eb5d-4027-a6f4-6eb6a6a8b3ef
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-18T13:00:02+00:00'
            elementCondition: null
            fieldUid: c5b33e76-5fe4-40c4-98a6-2f13e354ced5 # Knoppen
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 77b99e4f-1ed9-4f4a-a143-0e171b85f7e9
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-18T13:00:02+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: adb91080-5a53-4dc4-b87d-596bfb42efd9
            userCondition: null
          -
            dateAdded: '2024-10-18T13:00:02+00:00'
            elementCondition: null
            fieldUid: b9f016c9-d8b3-49f8-acbe-3337414dd097 # Artikelen
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 821acc0d-8ca9-4855-b6bb-68eb6e0c7cea
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-18T13:00:09+00:00'
            elementCondition: null
            fieldUid: 4f08eaca-189d-42fc-9987-cbed19663296 # Maximaal aantal berichten
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1d05b5f3-f153-4651-922e-6ee9b1aebe4d
            userCondition: null
            warning: null
            width: 100
        name: Inhoud
        uid: bb604c80-09df-448d-8f76-8aeca7947f92
        userCondition: null
handle: articlesGrid
hasTitleField: false
icon: newspaper
name: 'Artikel grid'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
