color: null
fieldLayouts:
  1b296801-0ebc-4003-96de-9b63cbb12187:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-10-17T10:40:42+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: a7e9a0fd-edcd-416b-b243-cadb933ae69e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-17T10:42:14+00:00'
            elementCondition: null
            fieldUid: 8d87bf9f-8546-434b-a971-6407e109f8aa # Blokken
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c65c5e7a-c047-4526-9257-c3d4eab416c7
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ea9521a3-eb99-43b5-9ecf-1e1447ba257f
        userCondition: null
handle: sharedBlocks
hasTitleField: true
icon: cubes
name: 'Gedeelde content blokken'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
