color: null
description: null
fieldLayouts:
  16610ec8-0d62-42a6-8839-4522cccaa5aa:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-10-17T12:58:11+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 437963f6-fffc-4014-921d-e13fd7b2315f # Tekst (uitgebreid)
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 20b37303-47ac-4b57-884e-7401a60a35ab
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3cd0ba4b-e0ec-4248-a095-643591dc081a
        userCondition: null
handle: text
hasTitleField: false
icon: font-case
name: Tekst
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
