color: null
fieldLayouts:
  3173e383-b0bc-4b0f-9e90-1541b5a32b2d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-10-17T10:48:42+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 3545e9dd-d192-4f22-b903-c24e026aeac8
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 612dcc1b-e9c6-4d81-9d88-655fdeb5ec85
        userCondition: null
handle: articleType
hasTitleField: true
icon: text
name: 'Artikel type'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
