color: null
fieldLayouts:
  952010c7-8136-48fa-932e-a39cc6488c91:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-10-18T08:56:46+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 6445e6f7-90fc-4d12-b34e-b3243702b8fd
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-18T08:58:28+00:00'
            elementCondition: null
            fieldUid: 86dfc9bd-0363-4046-a638-26e03cd481da # Afbeeldingen
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1e52c8a4-7bc9-4501-aa38-df6fbe8ca1ae
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-18T08:58:28+00:00'
            elementCondition: null
            fieldUid: 767c68f7-a42c-4402-a640-46af0c267fb7 # Afbeelding ratio
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 545c2311-1089-4bf0-98b7-0566de02c4bd
            userCondition: null
            warning: null
            width: 100
        name: Inhoud
        uid: 3cdae63a-9575-4f7b-9fbf-0b8af1241278
        userCondition: null
handle: images
hasTitleField: false
icon: image
name: Afbeelding
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
