color: null
fieldLayouts:
  423d92a3-0b09-4352-a62e-933eadb8f7d0:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-10-17T14:07:40+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f308d32a-0693-4745-a07d-a5470ad42806
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-17T14:09:57+00:00'
            elementCondition: null
            fieldUid: 86dfc9bd-0363-4046-a638-26e03cd481da # Afbeeldingen
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ae46fdda-3827-478d-a156-737c67818edc
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-17T14:09:57+00:00'
            elementCondition: null
            fieldUid: 767c68f7-a42c-4402-a640-46af0c267fb7 # Afbeelding ratio
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 36feded6-f341-4bfc-a5bb-9b72294b51d5
            userCondition: null
            warning: null
            width: 100
        name: Inhoud
        uid: f782a9ed-17d0-4127-98f3-a53b3f49f46a
        userCondition: null
handle: image
hasTitleField: false
icon: image
name: Afbeelding
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
