color: null
fieldLayouts:
  cc2988cf-a9e7-41e7-94d5-278b732fa737:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-10-18T13:25:38+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ce9df0ed-67ac-4610-a5e5-b9e24a4f8897
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-18T13:27:08+00:00'
            elementCondition: null
            fieldUid: afce72fb-dcb9-42e3-99d5-a4e1b6c32d71 # Media
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b17674b0-bde9-4dbf-9c00-9819b64a413f
            userCondition: null
            warning: null
            width: 100
        name: Inhoud
        uid: 5c679b94-3164-4d41-898b-576ac35dea49
        userCondition: null
handle: media
hasTitleField: false
icon: images
name: Media
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
