color: null
fieldLayouts:
  d39e7d22-0534-4ca1-9ee4-3a1bcad548f2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-10-17T10:27:30+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: d4852451-948d-4673-8ccd-10d90e6b4ad3
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-17T10:35:12+00:00'
            elementCondition: null
            fieldUid: f659e4e5-e885-4efe-918b-f9ea22bef550 # Afbeelding (enkel)
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e370e1a4-283b-4f5f-bbc9-70233f7e8d9c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-17T10:32:57+00:00'
            elementCondition: null
            fieldUid: 437963f6-fffc-4014-921d-e13fd7b2315f # Tekst (uitgebreid)
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e257d372-94fc-49f8-ad3d-e6f60041d1f4
            userCondition: null
            warning: null
            width: 100
        name: Header
        uid: 8cd3cf04-4dce-4a26-a816-6c16292cb81f
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-10-17T10:29:05+00:00'
            elementCondition: null
            fieldUid: 8d87bf9f-8546-434b-a971-6407e109f8aa # Blokken
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bf29d913-b595-4b3d-bed4-e6e1d326d7d2
            userCondition: null
            warning: null
            width: 100
        name: Inhoud
        uid: eab5f3d1-1233-4f13-a63d-5099e7432550
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-10-17T10:32:57+00:00'
            elementCondition: null
            fieldUid: c798cdf5-723e-4cdc-8ac1-6c527b1a14a6 # Bovenkop
            handle: cardPreHeading
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b0721b37-e4e4-4586-ba93-84d5451a5221
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-17T10:32:57+00:00'
            elementCondition: null
            fieldUid: d602da2a-239f-4f18-93fd-8047af89cdd0 # Kop
            handle: cardHeading
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 79da59f2-35f3-40f4-8f1e-c4997ab64a81
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-17T10:36:30+00:00'
            elementCondition: null
            fieldUid: 437963f6-fffc-4014-921d-e13fd7b2315f # Tekst (uitgebreid)
            handle: cardBody
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b9b48f33-7463-4c24-bfa3-bda0d0fa0769
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-17T10:35:12+00:00'
            elementCondition: null
            fieldUid: f659e4e5-e885-4efe-918b-f9ea22bef550 # Afbeelding (enkel)
            handle: cardImage
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3c252838-8629-42d4-90d3-d9c995939ecf
            userCondition: null
            warning: null
            width: 100
        name: Kaart
        uid: 94a12f18-3677-4bce-b55a-23ef2d7809e8
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-10-17T10:29:05+00:00'
            elementCondition: null
            fieldUid: 731e9cf0-d175-4a28-bd06-59e7f71e6ba1 # SEO Instellingen
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3f2bc3d0-de72-4bdb-b9fd-baf76e4f8fa1
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: d0c6a956-9453-41fa-bf94-b3b18ee5f993
        userCondition: null
handle: pages
hasTitleField: true
icon: page
name: "Pagina's"
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
