color: null
fieldLayouts:
  a6c943c0-c73c-46a3-865d-9eac8e28e0c1:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-10-18T13:00:00+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: a4cb5d76-f682-40d7-8279-d4112412d2aa
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-18T13:04:07+00:00'
            elementCondition: null
            fieldUid: d52247de-f951-467f-823c-4808b53741ca # Gedeeld blok
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a3522863-b089-4f06-a08b-8fcc3af84fd0
            userCondition: null
            warning: null
            width: 100
        name: Inhoud
        uid: d7b67f99-1d12-41a1-85fb-3e8e07ecf6a0
        userCondition: null
handle: sharedBlock
hasTitleField: false
icon: cubes
name: 'Gedeeld blok'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
