color: null
fieldLayouts:
  16610ec8-0d62-42a6-8839-4522cccaa5aa:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-10-17T10:24:00+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: bd726045-6533-4fb4-bea4-1bb4c8340dbc
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3cd0ba4b-e0ec-4248-a095-643591dc081a
        userCondition: null
handle: text
hasTitleField: true
icon: text
name: Tekst
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
