color: null
fieldLayouts:
  bf3c09f7-9526-4d00-afa3-366757350733:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-10-18T08:57:32+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 62a189e4-fec0-4d7c-889e-12498eb18abe
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-18T08:59:00+00:00'
            elementCondition: null
            fieldUid: 18915ee7-c649-4733-ab93-d96d10d1b46a # Video
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 47d6cdeb-0953-4712-bb4d-5ddbc7c31fc0
            userCondition: null
            warning: null
            width: 100
        name: Inhoud
        uid: 473d7c5d-e8cd-4eef-8cbc-655958eea1e7
        userCondition: null
handle: videos
hasTitleField: false
icon: video
name: Video
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
