columnSuffix: null
handle: buttonTheme
instructions: null
name: 'Knop thema'
searchable: false
settings:
  customOptions: false
  displayAsGraphic: null
  displayFullwidth: null
  options:
    -
      __assoc__:
        -
          - label
          - Primair
        -
          - showLabel
          - '1'
        -
          - value
          - primary
        -
          - imageUrl
          - ''
        -
          - imageAlign
          - left
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Secundair
        -
          - showLabel
          - '1'
        -
          - value
          - secondary
        -
          - imageUrl
          - ''
        -
          - imageAlign
          - left
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Alleen tekst'
        -
          - showLabel
          - '1'
        -
          - value
          - textOnly
        -
          - imageUrl
          - ''
        -
          - imageAlign
          - left
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: verbb\buttonbox\fields\Buttons
