columnSuffix: null
handle: sliderType
instructions: null
name: 'Slider type'
searchable: false
settings:
  displayAsGraphic: null
  displayFullwidth: null
  options:
    -
      __assoc__:
        -
          - label
          - 'Automatisch afspelen'
        -
          - showLabel
          - '1'
        -
          - value
          - inlineAutoplay
        -
          - imageUrl
          - ''
        -
          - imageAlign
          - left
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - 'Niet automatisch afspelen'
        -
          - showLabel
          - '1'
        -
          - value
          - inline
        -
          - imageUrl
          - ''
        -
          - imageAlign
          - left
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Popup
        -
          - showLabel
          - '1'
        -
          - value
          - popup
        -
          - imageUrl
          - ''
        -
          - imageAlign
          - left
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: verbb\buttonbox\fields\Buttons
