altTranslationKeyFormat: null
altTranslationMethod: site
fieldLayouts:
  cb63961c-a4a5-40fe-97f8-94300aad92e2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-10-17T11:30:38+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: dd1b8c86-6d7a-46c7-a05e-bff775597a1a
            userCondition: null
            warning: null
            width: 100
        name: Inhoud
        uid: c97aeda3-b3ee-4ee6-9a3a-4b252133d1e5
        userCondition: null
fs: images
handle: images
name: Afbeeldingen
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: images
transformSubpath: ''
