columnSuffix: null
handle: displayMethod
instructions: null
name: Weergave
searchable: false
settings:
  displayAsGraphic: null
  displayFullwidth: null
  options:
    -
      __assoc__:
        -
          - label
          - Pop-up
        -
          - showLabel
          - '1'
        -
          - value
          - popUp
        -
          - imageUrl
          - ''
        -
          - imageAlign
          - left
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Inline
        -
          - showLabel
          - '1'
        -
          - value
          - inline
        -
          - imageUrl
          - ''
        -
          - imageAlign
          - left
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Inline en automatisch afspelen'
        -
          - showLabel
          - '1'
        -
          - value
          - inlineAutoplay
        -
          - imageUrl
          - ''
        -
          - imageAlign
          - left
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: site
type: verbb\buttonbox\fields\Buttons
