columnSuffix: null
handle: externalUrl
instructions: null
name: 'Externe url'
searchable: true
settings:
  maxLength: 255
  typeSettings:
    __assoc__:
      -
        - url
        -
          __assoc__:
            -
              - allowRootRelativeUrls
              - ''
            -
              - allowAnchors
              - ''
  types:
    - url
    - email
    - tel
translationKeyFormat: null
translationMethod: none
type: craft\fields\Link
