columnSuffix: null
handle: figcaption
instructions: null
name: Ondertitel
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: '*'
  ckeConfig: 41e5ebbf-a8cc-4e04-95e6-9c888e2423e7 # Simple
  createButtonLabel: null
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: true
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
