columnSuffix: null
handle: seoSettings
instructions: null
name: 'SEO Instellingen'
searchable: false
settings:
  elementDisplayPreviewType: google
  facebookEnabledFields:
    - seoPreview
    - ogTitle
    - ogDescription
    - ogImage
    - ogImageDescription
  facebookTabEnabled: '1'
  generalEnabledFields:
    - seoPreview
    - mainEntityOfPage
    - seoTitle
    - seoDescription
    - seoKeywords
    - seoImage
    - seoImageDescription
    - robots
    - canonicalUrl
  generalTabEnabled: '1'
  sitemapEnabledFields: ''
  sitemapTabEnabled: ''
  twitterEnabledFields:
    - seoPreview
    - twitterCardType
    - twitterTitle
    - twitterDescription
    - twitterImage
    - twitterImageDescription
  twitterTabEnabled: '1'
translationKeyFormat: null
translationMethod: site
type: nystudio107\seomatic\fields\SeoSettings
